#!/usr/bin/env python

import sys
import argparse

# program options
parser = argparse.ArgumentParser(description='Annotate two lines with the positions where they are the same')
parser.add_argument('--case-sensitive', '-s', action='store_true',
        help='characters must have the same case to be called equal')

args = parser.parse_args()

# read the first line, skipping blank lines
line = sys.stdin.readline()[:-1]
while len(line) == 0:
    line = sys.stdin.readline()[:-1]

first_line = line

# read the second line, skipping blank lines
line = sys.stdin.readline()[:-1]
while len(line) == 0:
    line = sys.stdin.readline()[:-1]

second_line = line

# alignments have to be the same length
assert len(first_line) == len(second_line)

annotation = []
for i, j in zip(first_line, second_line):
    if not args.case_sensitive:
        i = i.upper()
        j = j.upper()

    if i == j:
        annotation.append('|')
    else:
        annotation.append(' ')

print first_line
print ''.join(annotation)
print second_line
